### PR TITLE
Cacheresult

### PR DESCRIPTION
**Pull request by chriskonstad**
Test strategy for:
1) Load up the page and search for 'AAPL'
2) Search for the stock symbol again, it should load almost instantly
  a) it should also include one tweet's worth of data
3) Open rails console and type
 `cached = SentimentCache.find_by(company_id: 204)`
 `cached.created_at = #{current created_at minus one day}`
 `cached.save`
  a) This assumes AAPL's `company_id` is 204, which it should be
4) Then, search for the symbol again and it should take time to load everything from twitter

[EDIT] Unit tests now cover this

### CODE REVIEW

**Comment by chriskonstad** [comment]
Note: Need to change from beginning_of_day to 24 hours ago.
Note: Need to add tests if we can pull twitter data in Travis.

**Comment by chriskonstad** [comment]
TODO: Add tests of analysis
TODO: Add tests of caching

**Comment by chriskonstad** [comment]
@bmwwoo @apfong @Sakibs someone please check this so we can get this merged in for Friday. Thanks!

**Comment by Sakibs** [comment]
I checked the file and I think it looks good. I like the test cases, we should write cases like that whenever we add a new feature.

:radio:

**Comment by apfong** [comment]
:100:/:100: 

Looks good, worked for me

**Pull request merged**
