### PR TITLE
Devise username

### PR DESCRIPTION
**Pull request by Sakibs**
Add username column to user table. Enable login with either username or email and password.

### CODE REVIEW

**Comment by chriskonstad** [comment]
Don't merge this.  You have commits in here that are already in origin/master. You need to pull the latest master and rebase your branch onto it.

**Comment by bmwwoo** [comment]
Might want to squash this if after the rebase it's still a lot of commits.

**Comment by chriskonstad** [comment]
Is it a "username" or the User's name?

**Comment by Sakibs** [comment]
A username, at this point

**Comment by chriskonstad** [comment]
Also, let's not squash commits, we should keep history intact.

**Comment by Sakibs** [comment]
Ive been trying to rebase it but I keep getting conflicts over and over again. Most of them are in files I fix multiple times like gemfile and gemfile.lock. The rebase just does not end. I might just make a new branch and do it again there.

**Comment by chriskonstad** [comment]
Can you not manually merge the changes?

**Comment by Sakibs** [comment]
I did when conflicts when come up. When I run git rebase continue, it shows other conflicts then I fix those and run git rebase continue and then previous conflicts show up from the first set that I already fixed. its really weird.

**Comment by Sakibs** [comment]
I think that creating a new clean branch is the better thing to do. This branch is pretty dirty with weird repeating commits and empty commits.

**Pull request closed without merging**
