### PR TITLE
Implement favoriting functionality

### PR DESCRIPTION
**Pull request by Sakibs**

### CODE REVIEW

**Comment by apfong** [comment]
Pretty cool, however I think I found a bug when trying to add and then delete a favorite. It works great when you add a stock, then look for another then try to delete, but if you try to add a stock and immediately remove it you cant.

**Comment by Sakibs** [comment]
I removed the remove favorite button because I could not find a proper way to generate new favorite button on new row entry. I will refactor a different way to do this in the main dashboard.

**Comment by Sakibs** [comment]
Need the backend favoriting code to be integrated for the main dashboard.

**Comment by Sakibs** [comment]
@chriskonstad @apfong @bmwwoo Can you verify this so I can integrate the db code in?

**Comment by chriskonstad** [comment]
Why do you have already merged commits in here?

**Comment by Sakibs** [comment]
Merged commits? I did a rebase on a freshly pulled master. Even then It thought I diverged from the remote and it wanted me to pull. I pulled but no file actually changed. I was not too sure why...

**Comment by chriskonstad** [comment]
Commits ` 5d3cfc7`, `d2193f6`, `6814903` and `1f2fe2a` shouldn't be in this PR

**Comment by Sakibs** [comment]
Im sorry guys, I didn't merge into master. All I did was rebase with master and somehow those commits got in. What do you suggest I do?

**Comment by chriskonstad** [comment]
No worries dude. What commands did you run?

**Comment by Sakibs** [comment]
I had a few commits on my branch and it was behind the master which changed since I forked. I did the following workflow

git checkout master
git pull
git checkout favorites
git rebase master
- At this point rebase was successful, no conflicts detected, happened in 1 go
- Tried to push to remote favorite. Said my branch is behind 1 commit and it suggested that I pull remote so I did
git pull. 
- this is why I have an empty merge commit merging remote favorite into my favorite

Thats it. I have no idea how those commits got in

**Comment by chriskonstad** [comment]
Hmm.... When you pulled remote, how did you pull?  I've rebased this branch onto master on my machine and removed the extraneous commits. Want me to force push the changes up here?

**Comment by Sakibs** [comment]
Just did 
git pull
after switching back to favorites
This http://stackoverflow.com/questions/8939977/git-push-rejected-after-feature-branch-rebase is the exact same problem I had when I tried to push back to remote. It did not let me push it and suggested I pull.
I think I should have just done a force push.

**Comment by Sakibs** [comment]
You can go ahead and do the force push

**Comment by chriskonstad** [comment]
Okay I'll push when the tests finish running.  Ah. You can't directly push after rebasing because you've changed your history, and so Git doesn't know how to handle that. You have to force push

**Comment by chriskonstad** [comment]
Also, note for the future: You can preview what changes you will be pushing by running `git diff master...<branch_name>`.  Also, when you force push, use `git push --force-with-lease` to make sure you're not overriding any commits that you don't know about.

**Comment by chriskonstad** [comment]
Btw, ran the tests and tried it out on my computer and :+1: lgtm

**Comment by Sakibs** [comment]
Did it get those commits from master because I did the pull and merge?

**Comment by Sakibs** [comment]
:fireworks: :fireworks: :fireworks:

**Comment by chriskonstad** [comment]
I think so. `git pull` is just a `git fetch && git merge` so that probably introduced the commits.

**Pull request merged**
