### PR TITLE
Added Company model and seed data

### PR DESCRIPTION
**Pull request by chriskonstad**
All of the current NASDAQ symbols are loaded up :)

Need to do "rake db:reset" not "rake db:seed" otherwise the unique
symbol check will fail. Be warned!

### CODE REVIEW

**Comment by chriskonstad** [comment]
Just did a rebase onto master to fix merge conflicts caused by an outdated `db/schema.rb`.

**Comment by bmwwoo** [comment]
How do we check this? @chriskonstad

**Comment by chriskonstad** [comment]
check if `/api/symbols/json` returns a json array of something like 3092 tickers.

**Comment by bmwwoo** [comment]
LGTM :fallen_leaf:

**Pull request merged**
